#= require vendor/modernizr
#= require vendor/jquery
#= require vendor/jquery-ui
#= require vendor/jquery.tmpl
#= require vendor/jquery.lifestream
#= require vendor/jquery.timeago
#= require vendor/jquery.fitvids
#= require bootstrap
#= require toISO8601
#= require lifestream
#= require timeago
#= require fitvids
# require vendor/jquery.oembed
# require oembed
